### ISSUE TITLE
Exception at 0000000100010930: EReadError:

### ISSUE THREAD

**Issue by wgetnz** [0xsp-SRD/mortar#4] opened 2021-12-29 10:11 UTC
C:\>deliver.exe -d -f bin.enc
Exception at 0000000100010930: EReadError:
Stream read error

**Comment by lawrenceamer** [comment] 2021-12-29 12:15
that issue is duplicate of https://github.com/0xsp-SRD/mortar/commit/18736a408b53ad0ff3d62c97a4d08b976e14518d and already fixed, fetch new clone of encryptor and make sure to use correct arch

**Closed by lawrenceamer** 2021-12-29 12:15 UTC
